export const ErrorCode = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_TOKEN_INVALID: 'AUTH_002',
  AUTH_TOKEN_EXPIRED: 'AUTH_003',
  AUTH_SESSION_REVOKED: 'AUTH_004',
  AUTH_TOKEN_REUSED: 'AUTH_005',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_006',
  PERMISSION_DENIED: 'PERMISSION_001',
  TENANT_CONTEXT_INVALID: 'TENANT_001',
  TENANT_BRANCH_REQUIRED: 'TENANT_002',
  TENANT_BRANCH_FORBIDDEN: 'TENANT_003',
  VALIDATION_FAILED: 'VALIDATION_001',
  DOMAIN_CONFLICT: 'DOMAIN_001',
  BUSINESS_RULE_VIOLATION: 'DOMAIN_002',
  CONCURRENCY_CONFLICT: 'DOMAIN_003',
  DATABASE_ERROR: 'DATABASE_001',
  NOT_FOUND: 'HTTP_404',
  RATE_LIMITED: 'HTTP_429',
  SECURITY_ORIGIN_DENIED: 'SECURITY_001',
  INTERNAL_ERROR: 'INTERNAL_001',
} as const

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode]
